# Generated by Django 4.1.5 on 2023-02-10 17:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_sap', models.CharField(blank=True, error_messages={'unique': 'Ya existe un artículo con este código'}, help_text='Código del Artículo', max_length=20, null=True, verbose_name='Código')),
                ('family', models.CharField(blank=True, max_length=100, null=True, verbose_name='Familia')),
                ('sub_family', models.CharField(blank=True, max_length=100, null=True, verbose_name='Sub-Familia')),
                ('kind_of_existence', models.CharField(blank=True, max_length=100, null=True, verbose_name='Tipo de Existencia')),
                ('description', models.CharField(blank=True, max_length=100, null=True, verbose_name='Descripción')),
                ('stock', models.IntegerField(blank=True, default=0, null=True, verbose_name='Stock')),
                ('unit_measurement', models.CharField(blank=True, max_length=20, null=True, verbose_name='Unidad de Medida')),
                ('money', models.CharField(blank=True, max_length=20, null=True, verbose_name='Moneda')),
                ('value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor')),
            ],
            options={
                'verbose_name': 'Artículo',
                'verbose_name_plural': 'Artículos',
                'ordering': ['family'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalArticle',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('code_sap', models.CharField(blank=True, error_messages={'unique': 'Ya existe un artículo con este código'}, help_text='Código del Artículo', max_length=20, null=True, verbose_name='Código')),
                ('family', models.CharField(blank=True, max_length=100, null=True, verbose_name='Familia')),
                ('sub_family', models.CharField(blank=True, max_length=100, null=True, verbose_name='Sub-Familia')),
                ('kind_of_existence', models.CharField(blank=True, max_length=100, null=True, verbose_name='Tipo de Existencia')),
                ('description', models.CharField(blank=True, max_length=100, null=True, verbose_name='Descripción')),
                ('stock', models.IntegerField(blank=True, default=0, null=True, verbose_name='Stock')),
                ('unit_measurement', models.CharField(blank=True, max_length=20, null=True, verbose_name='Unidad de Medida')),
                ('money', models.CharField(blank=True, max_length=20, null=True, verbose_name='Moneda')),
                ('value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Artículo',
                'verbose_name_plural': 'historical Artículos',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
