# Generated by Django 4.1.5 on 2023-02-10 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='code_sap',
            field=models.CharField(default='adsadsdas', error_messages={'unique': 'Ya existe un artículo con este código'}, help_text='Código del Artículo', max_length=20, unique=True, verbose_name='Código'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='historicalarticle',
            name='code_sap',
            field=models.CharField(db_index=True, default='qweqweqwe', error_messages={'unique': 'Ya existe un artículo con este código'}, help_text='Código del Artículo', max_length=20, verbose_name='Código'),
            preserve_default=False,
        ),
    ]
