# Generated by Django 4.1.5 on 2023-02-22 15:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0002_alter_article_code_sap_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Requirements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Fecha')),
                ('product', models.CharField(blank=True, max_length=100, null=True, verbose_name='Producto')),
                ('description', models.CharField(blank=True, max_length=100, null=True, verbose_name='Descripción')),
                ('quantity', models.IntegerField(blank=True, default=0, null=True, verbose_name='Cantidad')),
                ('unit_measurement', models.CharField(blank=True, max_length=20, null=True, verbose_name='Unidad de Medida')),
                ('status', models.CharField(choices=[('Pendiente', 'Pendiente'), ('Aprobado', 'Aprobado'), ('Rechazado', 'Rechazado'), ('Finalizado', 'Finalizado')], default='Pendiente', max_length=20, verbose_name='Estado')),
                ('observation', models.TextField(blank=True, max_length=100, null=True, verbose_name='Observación')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Requerimiento',
                'verbose_name_plural': 'Requerimientos',
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalRequirements',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('date', models.DateField(blank=True, editable=False, verbose_name='Fecha')),
                ('product', models.CharField(blank=True, max_length=100, null=True, verbose_name='Producto')),
                ('description', models.CharField(blank=True, max_length=100, null=True, verbose_name='Descripción')),
                ('quantity', models.IntegerField(blank=True, default=0, null=True, verbose_name='Cantidad')),
                ('unit_measurement', models.CharField(blank=True, max_length=20, null=True, verbose_name='Unidad de Medida')),
                ('status', models.CharField(choices=[('Pendiente', 'Pendiente'), ('Aprobado', 'Aprobado'), ('Rechazado', 'Rechazado'), ('Finalizado', 'Finalizado')], default='Pendiente', max_length=20, verbose_name='Estado')),
                ('observation', models.TextField(blank=True, max_length=100, null=True, verbose_name='Observación')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'historical Requerimiento',
                'verbose_name_plural': 'historical Requerimientos',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
