# Generated by Django 4.1.5 on 2023-02-22 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_alter_historicalrequirements_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalrequirements',
            name='observation',
        ),
        migrations.RemoveField(
            model_name='requirements',
            name='observation',
        ),
    ]
