# Generated by Django 4.1.5 on 2023-02-13 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_historicaluseraccount_address_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicalusercategory',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Categoría ', 'verbose_name_plural': 'historical Categorías'},
        ),
        migrations.AlterModelOptions(
            name='usercategory',
            options={'verbose_name': 'Categoría ', 'verbose_name_plural': 'Categorías'},
        ),
        migrations.AlterField(
            model_name='historicaluseraccount',
            name='role',
            field=models.CharField(choices=[('Admin', 'Admin'), ('Técnico', 'Technical'), ('Visualizador', 'Visualizer'), ('Editor', 'Editor')], default='Visualizador', max_length=13, verbose_name='Rol'),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='role',
            field=models.CharField(choices=[('Admin', 'Admin'), ('Técnico', 'Technical'), ('Visualizador', 'Visualizer'), ('Editor', 'Editor')], default='Visualizador', max_length=13, verbose_name='Rol'),
        ),
    ]
