# Generated by Django 4.1.5 on 2023-02-24 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_thirdparties_historicalthirdparties'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaluseraccount',
            name='role',
            field=models.CharField(choices=[('Técnico', 'Technical'), ('Visualizador', 'Visualizer'), ('Editor', 'Editor'), ('Supervisor', 'Supervisor'), ('Compras', 'Compras')], default='Editor', max_length=13, verbose_name='Rol'),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='role',
            field=models.CharField(choices=[('Técnico', 'Technical'), ('Visualizador', 'Visualizer'), ('Editor', 'Editor'), ('Supervisor', 'Supervisor'), ('Compras', 'Compras')], default='Editor', max_length=13, verbose_name='Rol'),
        ),
    ]
