# Generated by Django 4.1.5 on 2023-02-16 15:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import simple_history.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('assets', '0001_initial'),
        ('config', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_report', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de reporte')),
                ('date_start', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de inicio')),
                ('date_finish', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Fecha de finalización')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('activities', models.TextField(blank=True, null=True, verbose_name='Actividades')),
                ('status', models.BooleanField(default=False, verbose_name='Estado')),
                ('observations', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('planned', models.BooleanField(default=False, verbose_name='Planificado')),
                ('criticity', models.PositiveSmallIntegerField(default=1, verbose_name='Criticidad')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='assets.physical', verbose_name='Activo')),
                ('failure', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='config.failure', verbose_name='Origen de falla')),
                ('technical', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL, verbose_name='Técnico')),
                ('tools', models.ManyToManyField(blank=True, to='assets.tool', verbose_name='Herramientas')),
                ('type_maintenance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='config.type', verbose_name='Tipo de mantenimiento')),
            ],
            options={
                'verbose_name': 'Orden de Trabajo',
                'verbose_name_plural': 'Ordenes de Trabajo',
                'ordering': ['date_report'],
            },
        ),
        migrations.CreateModel(
            name='WorkRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_report', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de reporte')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='assets.physical', verbose_name='Activo')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
                ('work_order', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='management.workorder', verbose_name='Orden de trabajo')),
            ],
            options={
                'verbose_name': 'Solicitud de trabajo',
                'verbose_name_plural': 'Solicitudes de trabajo',
                'ordering': ['-date_report'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalWorkOrder',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('date_report', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de reporte')),
                ('date_start', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de inicio')),
                ('date_finish', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Fecha de finalización')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('activities', models.TextField(blank=True, null=True, verbose_name='Actividades')),
                ('status', models.BooleanField(default=False, verbose_name='Estado')),
                ('observations', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('planned', models.BooleanField(default=False, verbose_name='Planificado')),
                ('criticity', models.PositiveSmallIntegerField(default=1, verbose_name='Criticidad')),
                ('created', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('asset', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='assets.physical', verbose_name='Activo')),
                ('failure', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='config.failure', verbose_name='Origen de falla')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('type_maintenance', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='config.type', verbose_name='Tipo de mantenimiento')),
            ],
            options={
                'verbose_name': 'historical Orden de Trabajo',
                'verbose_name_plural': 'historical Ordenes de Trabajo',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
