# Generated by Django 4.1.5 on 2023-02-16 15:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_article_code_sap_and_more'),
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResourceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Cantidad')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='store.article', verbose_name='Artículo')),
                ('work_order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='management.workorder', verbose_name='Orden de trabajo')),
            ],
            options={
                'verbose_name': 'Recurso',
                'verbose_name_plural': 'Recursos',
                'ordering': ['work_order'],
            },
        ),
        migrations.AddField(
            model_name='workorder',
            name='resources_used',
            field=models.ManyToManyField(blank=True, through='management.ResourceItem', to='store.article', verbose_name='Recursos utilizados'),
        ),
    ]
