# Generated by Django 4.1.5 on 2023-02-16 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_resourceitem_workorder_resources_used'),
    ]

    operations = [
        migrations.AddField(
            model_name='resourceitem',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Precio'),
        ),
    ]
