# Generated by Django 4.1.5 on 2023-02-16 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0003_resourceitem_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resourceitem',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, verbose_name='Precio'),
        ),
    ]
