# Generated by Django 4.1.5 on 2023-02-16 17:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0004_alter_resourceitem_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resourceitem',
            name='work_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='resources_order', to='management.workorder', verbose_name='Orden de trabajo'),
        ),
    ]
