# Generated by Django 4.1.5 on 2023-02-16 17:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_article_code_sap_and_more'),
        ('management', '0005_alter_resourceitem_work_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resourceitem',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='resources_article', to='store.article', verbose_name='Artículo'),
        ),
    ]
