# Generated by Django 4.1.5 on 2023-02-18 18:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0001_initial'),
        ('management', '0006_alter_resourceitem_article'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workorder',
            name='asset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='work_orders', to='assets.physical', verbose_name='Activo'),
        ),
    ]
