# Generated by Django 4.1.5 on 2023-02-23 15:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('management', '0007_alter_workorder_asset'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalworkorder',
            name='supervisor',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Supervisor'),
        ),
        migrations.AddField(
            model_name='historicalworkorder',
            name='validated',
            field=models.BooleanField(default=False, verbose_name='Validado'),
        ),
        migrations.AddField(
            model_name='workorder',
            name='supervisor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='work_orders_supervisor', to=settings.AUTH_USER_MODEL, verbose_name='Supervisor'),
        ),
        migrations.AddField(
            model_name='workorder',
            name='validated',
            field=models.BooleanField(default=False, verbose_name='Validado'),
        ),
    ]
